// <auto-generated />
using Foods.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Foods.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class FoodContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Foods.Models.Food", b =>
                {
                    b.Property<int>("FoodId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Calories");

                    b.Property<string>("FoodGroup");

                    b.Property<string>("Name");

                    b.HasKey("FoodId");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("Foods.Models.Rest", b =>
                {
                    b.Property<int>("RestId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Location");

                    b.Property<string>("Menu");

                    b.Property<string>("RestName");

                    b.Property<string>("Style");

                    b.HasKey("RestId");

                    b.ToTable("Rests");
                });

            modelBuilder.Entity("Foods.Models.RestFood", b =>
                {
                    b.Property<int>("FoodId");

                    b.Property<int>("RestId");

                    b.HasKey("FoodId", "RestId");

                    b.HasIndex("RestId");

                    b.ToTable("RestFoods");
                });

            modelBuilder.Entity("Foods.Models.RestFood", b =>
                {
                    b.HasOne("Foods.Models.Food", "Food")
                        .WithMany("RestFoods")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Foods.Models.Rest", "Rest")
                        .WithMany("RestFoods")
                        .HasForeignKey("RestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
